language: php

php:
    - 7.2
    - 7.3
    - 7.4

dist: trusty
sudo: false

# 执行前需要运行的命令
install: travis_retry composer install --no-interaction --prefer-source

# 主要构建命令
script: vendor/bin/phpunit --verbose